import type { Metadata } from 'next'
import { Spline_Sans, Spline_Sans_Mono } from 'next/font/google'
import './globals.css'

const splineSans = Spline_Sans({
  subsets: ['latin'],
  variable: '--font-spline-sans',
})
const splineSansMono = Spline_Sans_Mono({
  subsets: ['latin'],
  variable: '--font-spline-sans-mono',
})

export const metadata: Metadata = {
  title: 'MP Grafícos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${splineSans.variable} ${splineSansMono.variable} antialiased bg-background-color`}
      >
        {children}
      </body>
    </html>
  )
}
